### ISSUE TITLE
remove unused prefect-related functions

### ISSUE THREAD

**Issue by decembboy** [DalgoT4D/DDP_backend#762] opened 2024-07-20 11:05 UTC
@fatchat  I removed unused functions  kindly verify. 

https://docs.google.com/spreadsheets/d/1sgh5NtW8MEcYiUcs9GaojtqsTR2Vk_zpX5bF4ef6zzs/edit#gid=0

**Comment by decembboy** [comment] 2024-07-20 11:06
I removed unused  function kindly verify.

**Comment by fatchat** [comment] 2024-07-22 17:35
hello @decembboy 

you need to fork the repo, remove the unused functions, commit and push to your forked repo, and then open a pull-request asking to merge your changes into this repo. when you do that i will be able to see your changes and either accept them or ask you to make changes before accepting

you can google "github pull request" to learn about this flow. thanks for your interest and i look forward to your PR

**Comment by fatchat** [comment] 2024-07-22 17:35
duplicate of #542

**Closed by fatchat** 2024-07-22 17:35 UTC
