### ISSUE TITLE
Need status of manual sync

### ISSUE THREAD

**Issue by siddhant3030** [DalgoT4D/DDP_backend#420] opened 2024-01-08 09:23 UTC
The facility sheet connection failed today so I did the manual sync but from the logs I don;t know if the sync worked or not. 

two issues are here 
1. Why did the scheduled sync failed? 
2. Clear way to know if the manual sync worked or not. Very confusing for any user right now

The error thrown was this 
```
-
- JSON schema validation failed.
- errors: $.auth_type: must be a constant value Client, $.client_id: is missing but it is required, $.client_secret: is missing but it is required, $.refresh_token: is missing 
```

**Comment by fatchat** [comment] 2024-01-08 16:25
1. the scheduled sync failed because the pipeline ran "dbt clean" after "dbt deps"; see https://github.com/DalgoT4D/DDP_backend/pull/418

2. agree this is required, duplicate of https://github.com/DalgoT4D/DDP_backend/issues/417

closing this issue in favour of 417

**Closed by fatchat** 2024-01-08 16:25 UTC
Labels: enhancement
